// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf5kk0vXD-3BuU_x33v7KlbbWR89W4cd8',
    appId: '1:302652676190:web:968ab731172ed2cf34fccf',
    messagingSenderId: '302652676190',
    projectId: 'recipe-browser-andonovasofija',
    authDomain: 'recipe-browser-andonovasofija.firebaseapp.com',
    storageBucket: 'recipe-browser-andonovasofija.firebasestorage.app',
    measurementId: 'G-4HW7S128CQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Y4iwxCnemHPTvko41IuFlDztV5MpB4I',
    appId: '1:302652676190:android:d6fe19616348733634fccf',
    messagingSenderId: '302652676190',
    projectId: 'recipe-browser-andonovasofija',
    storageBucket: 'recipe-browser-andonovasofija.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV4UUgFzld14pTEjwoplJ5AnLAYL11A7Y',
    appId: '1:302652676190:ios:40d19e04478edad134fccf',
    messagingSenderId: '302652676190',
    projectId: 'recipe-browser-andonovasofija',
    storageBucket: 'recipe-browser-andonovasofija.firebasestorage.app',
    iosBundleId: 'com.example.recipesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV4UUgFzld14pTEjwoplJ5AnLAYL11A7Y',
    appId: '1:302652676190:ios:40d19e04478edad134fccf',
    messagingSenderId: '302652676190',
    projectId: 'recipe-browser-andonovasofija',
    storageBucket: 'recipe-browser-andonovasofija.firebasestorage.app',
    iosBundleId: 'com.example.recipesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf5kk0vXD-3BuU_x33v7KlbbWR89W4cd8',
    appId: '1:302652676190:web:2fc24d84176c218b34fccf',
    messagingSenderId: '302652676190',
    projectId: 'recipe-browser-andonovasofija',
    authDomain: 'recipe-browser-andonovasofija.firebaseapp.com',
    storageBucket: 'recipe-browser-andonovasofija.firebasestorage.app',
    measurementId: 'G-8BDGMPH3Z4',
  );
}
